name: MLOps Pipeline

on:
  pull_request:
    branches: [ "main" ]
  # Allow mannually trigger
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: action/checkout@v2
    - name: Set up Python 3.12
      uses: action/Python-for-MLOps-pipeline@v1
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        make install
    - name: Lnt with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
